#!/usr/bin/env bash

die () {
	printf '\033[31mfatal:\033[m %b\n' "$@" >&2
	exit 1
}

gtktheme="$HOME/.config/gtk-3.0/settings.ini"
[[ -e $gtktheme ]] || die "gtk-3.0/settings.ini cannot be found"

while read -r line; do
	if [[ $line = *gtk-font-name* ]]; then
		font="${line##*=}"
	break
	fi
done < "$gtktheme"
[[ -z $font ]] && die "settings.ini contains no font name"

# print without font size
printf '%b\n' "${font%\ *}"
