#!/usr/bin/env bash
#
# hhhconf - a config tool for tint2
#
# shellcheck disable=2154 source=/dev/null

die () {
	printf '\033[31mfatal:\033[m %b\n' "$@" >&2
	exit 1
}

log () {
	printf '\033[32m=>\033[m %s\n' "$@"
}

xtype () {
	type "$1" >/dev/null 2>&1 || die "depend on $1"
}

read_sleep () {
	read -rst "${1:-1}" -N 999
	return 0
}

backup () {
	local files_to_backup="${HOME}/.config/tint2/tint2rc"
	local backup_dir
	backup_dir="${HOME}/.cache/hhhconf/backup/$(date +%Y%m%d%H%M%S%N)"
	test -d "${backup_dir}" && die "duplicate backup directory"
	mkdir -p "${backup_dir}"
	log "backup to $backup_dir"
	for f in ${files_to_backup}
	do
		test -e "${f}" || continue
		cp -p "${f}" "${backup_dir}"
	done
}

say () {
	printf "${g_print_col}%b\n" "$@"
}

set_color () {
	local color=$1 r g b
	case "${color:=7}" in
		"#"*)
			(( r=16#${color:1:2} ))
			(( g=16#${color:3:2} ))
			(( b=16#${color:5:6} ))
			: "\\e[38;2;${r};${g};${b}m"
			;;
		[0-9]*)	: "\\e[38;5;${color}m" ;;
		*)	: "\\e[38;5;7m" ;;
	esac
	printf -v g_print_col '%b' "$_"
}

preview_colors () {
	local count=0
	local i
	for i in {0..15}; do
		set_color 7
		printf "${g_print_col}%2d " "$count"
		set_color $i
		printf "${g_print_col}%b" "███  "
		set_color 7
		[[ $i -eq 7 ]] && printf "\n"
		(( count++ ))
	done
	printf "\n"
}

apply_gtk_font_to_tint2 () {
	backup
	local font=$(hhhconf-gtkfont)
	hhhconf-t2 -F
	hhhconf-t2 -p "task_font" "$font"
	hhhconf-t2 -p "taskbar_name_font" "$font"
	hhhconf-t2 -p "time1_font" "$font"
	hhhconf-t2 -p "time2_font" "$font"
	hhhconf-t2 -p "tooltip_font" "$font"
	hhhconf-t2 -p "bat1_font" "$font"
	hhhconf-t2 -p "bat2_font" "$font"
	hhhconf-t2 -p "execp_font" "$font"
	hhhconf-t2 -p "button_font" "$font"
}

pywal_tint2 () {
	backup
	local wal_colours="${HOME}/.cache/wal/colors.sh"
	[[ -e $wal_colours ]] || die "cannot find $wal_colours"
	. "$wal_colours"
#	hhhconf-t2 -s panel background_color "$background 100"
	hhhconf-t2 -s task_active background_color "$color1 100"
	hhhconf-t2 task_background_id 0
}

hard_restart () {
	log "restart $1"
	killall "$1" ; nohup "$1" >/dev/null 2>&1 &
	disown
}

print_commands () {
	printf "%b" "\
c = view terminal colors\n\
f = apply gtk3 font to tint2\n\
h = show available commands\n\
i = import tint2rc\n\
p = apply pywal to tint2\n\
t = restart tint2\n\
- = sleep one second\n\
q = quit\n"
}

bad_command () {
	log "($1) is not a recognised command"
}

process_command_string () {
	# process one character at a time
	for ((i=0;i<${#1};i++)); do
		case "${1:$i:1}" in
			c) preview_colors ;;
			f) apply_gtk_font_to_tint2 ;;
			i) backup ; hhhconf-import ;;
			t) hard_restart tint2 ;;
			p) pywal_tint2 ;;
			h|\?) print_commands ;;
			q) return 1 ;;
			-) read_sleep 1 ;;
			'') ;;
			*) bad_command "$1" ;;
		esac
	done
}

prompt () {
	local cmd=
	printf "%b" "\033[32mWhat now>\033[m "
	read -r cmd
	process_command_string "$cmd"
}

await_user_command () {
	print_commands
	while :
	do
		prompt || break
	done
}

usage () {
	printf "%b\n" "usage: hhhconf [-h] [<commands>]"
	exit 0
}

args() {
	case $1 in
		-h)	usage ;;
		*)	process_command_string "$1" ;;
	esac
}

main() {
	xtype tint2
	if [[ $# -gt 0 ]]; then
		args "$@"
	else
		await_user_command
	fi
}

main "$@"
